from django.urls import include, path

# This should contain paths related to registry ONLY
urlpatterns = [
    # Forms Registry
    'cpovc_forms.views',
    path(r'^', 'forms_home', name='forms'),
    path(r'^followups/', 'forms_registry',
         name='forms_registry'),

    # Documents Manager
    path('documents_manager/', 'documents_manager',
         name='documents_manager'),
    path('documents_manager_search/', 'documents_manager_search',
         name='documents_manager_search'),

    # Case Record Sheet paths
    path('crs/', 'case_record_sheet',
         name='case_record_sheet'),
    path('crs/new/(<id>\d+)/', 'new_case_record_sheet',
         name='new_case_record_sheet'),
    path('crs/view/(<id>\w+)/', 'view_case_record_sheet',
         name='view_case_record_sheet'),
    path('crs/edit/(<id>\w+)/', 'edit_case_record_sheet',
         name='edit_case_record_sheet'),
    path('crs/delete/(<id>\w+)/', 'delete_case_record_sheet',
         name='delete_case_record_sheet'),

    # Alternative Family Care paths
    path('afc/', 'alternative_family_care',
         name='alternative_family_care'),
    path('afc/new/(<id>\d+)/', 'new_alternative_family_care',
         name='new_alternative_family_care'),
    path('afc/edit/(<id>\w+)/', 'edit_alternative_family_care',
         name='edit_alternative_family_care'),
    path('afc/view/(<id>\w+)/', 'view_alternative_family_care',
         name='view_alternative_family_care'),

    # Residential Placement
    path('placement/save/', 'save_placement',
         name='save_placement'),
    path('placement/view/(<id>\w+)/', 'view_placement',
         name='view_placement'),
    path('placement/edit/(<id>\w+)/', 'edit_placement',
         name='edit_placement'),
    path('placement/delete/', 'delete_placement',
         name='delete_placement'),
    path('placement/',
         'residential_placement', name='residential_placement'),
    path('^placement/(<id>\d+)/',
         'placement', name='placement'),

    # Residential Placement FollowUp
    path('placement_followup/(<id>\d+)/',
         'placement_followup', name='placement_followup'),
    path('save_placementfollowup/',
         'save_placementfollowup', name='save_placementfollowup'),
    path('view_placementfollowup/',
         'view_placementfollowup', name='view_placementfollowup'),
    path('edit_placementfollowup/', 'edit_placementfollowup',
         name='edit_placementfollowup'),
    path('delete_placementfollowup/', 'delete_placementfollowup',
         name='delete_placementfollowup'),

    # Case Events (Encounters/Court Sessions/Referrals/Case
    # Closure/Summons)
    path('case_events/(?P<id>\w+)/', 'case_events',
         name='case_events'),
    # ---------------------------------------------------------
    path('save_encounter/', 'save_encounter',
         name='save_encounter'),
    path('view_encounter/', 'view_encounter',
         name='view_encounter'),
    path('edit_encounter/', 'edit_encounter',
         name='edit_encounter'),
    path('delete_encounter/', 'delete_encounter',
         name='delete_encounter'),
    # ----------------------------------------------------------
    path('save_court/', 'save_court', name='save_court'),
    path('view_court/', 'view_court',
         name='view_court'),
    path('edit_court/', 'edit_court',
         name='edit_court'),
    path('delete_court/', 'delete_court',
         name='delete_court'),
    # ----------------------------------------------------------
    path('save_summon/', 'save_summon', name='save_summon'),
    path('edit_summon/', 'edit_summon', name='edit_summon'),
    path('view_summon/', 'view_summon', name='view_summon'),
    path('delete_summon/', 'delete_summon',
         name='delete_summon'),
    # ----------------------------------------------------------
    path('save_closure/', 'save_closure', name='save_closure'),
    path('edit_closure/', 'edit_closure', name='edit_closure'),
    path('view_closure/', 'view_closure', name='view_closure'),
    path('delete_closure/', 'delete_closure', name='delete_closure'),

    # Referrals
    path('delete_referral/', 'delete_referral',
         name='delete_referral'),

    # Management paths
    path('manage_refferal/', 'manage_refferal',
         name='manage_refferal'),
    path('manage_refferal001/', 'manage_refferal001',
         name='manage_refferal001'),
    path('manage_refferal002/', 'manage_refferal002',
         name='manage_refferal002'),
    path('manage_refferal003/', 'manage_refferal003',
         name='manage_refferal003'),
    path('manage_casecategory001/', 'manage_casecategory001',
         name='manage_casecategory001'),
    path('manage_casecategory002/', 'manage_casecategory002',
         name='manage_casecategory002'),
    path('manage_casecategory003/', 'manage_casecategory003',
         name='manage_casecategory003'),
    path('manage_casecategory004/', 'manage_casecategory004',
         name='manage_casecategory004'),
    path('manage_encounters001/', 'manage_encounters001',
         name='manage_encounters001'),
    path('manage_encounters004/', 'manage_encounters004',
         name='manage_encounters004'),
    path('manage_case_events/', 'manage_case_events',
         name='manage_case_events'),
    path('manage_placementfollowup/', 'manage_placementfollowup',
         name='manage_placementfollowup'),
    path('manage_schools/', 'manage_schools',
         name='manage_schools'),
    path('manage_countries/', 'manage_countries',
         name='manage_countries'),
    path('manage_casehistory/', 'manage_casehistory',
         name='manage_casehistory'),
    path('manage_service_category/', 'manage_service_category',
         name='manage_service_category'),
    path('manage_form_type/', 'manage_form_type',
         name='manage_form_type'),
    # ---------------------------------------------------------------
    path('userorgunits_lookup/', 'userorgunits_lookup',
         name='userorgunits_lookup'),
    path('usersubcounty_lookup/', 'usersubcounty_lookup',
         name='usersubcounty_lookup'),
    path('userward_lookup/', 'userward_lookup',
         name='userward_lookup'),
    path('generate_serialnumber/', 'generate_serialnumber',
         name='generate_serialnumber'),
    path('getJsonObject001/', 'getJsonObject001',
         name='getJsonObject001'),

    # Search paths
    path('ovc_search/', 'ovc_search', name='ovc_search'),

    # School & Bursary paths
    path('education/', 'background_details',
         name='background_details'),
    path('education/new/(?P<id>\d+)/',
         'new_education_info', name='new_education_info'),
    path('education/edit/(?P<id>\w+)/',
         'edit_education_info', name='edit_education_info'),
    path('education/view/(?P<id>\w+)/',
         'view_education_info', name='view_education_info'),
    path('education/delete/(?P<id>\w+)/',
         'delete_education_info', name='delete_education_info'),
    # -----------------------------------------------------------------
    path('school/',
         'new_school', name='new_school'),
    # ------------------------------------------------------------------
    path('bursary/new/',
         'new_bursary_info', name='new_bursary_info'),
    path('bursary/edit/',
         'edit_bursary_info', name='edit_bursary_info'),
    path('bursary/view/',
         'view_bursary_info', name='view_bursary_info'),
    path('bursary/delete/',
         'delete_bursary_info', name='delete_bursary_info'),
    path('bursary/followup/(?P<id>\d+)/',
         'bursary_followup', name='bursary_followup'),
    path('bursary/manage/',
         'manage_bursary', name='manage_bursary'),
    # OVC Care - CSI
    path('csi/',
         'csi', name='csi'),
    path('csi/new/(?P<id>\d+)/',
         'new_csi', name='new_csi'),
    path('csi/edit/(?P<id>\w+)/',
         'edit_csi', name='edit_csi'),
    path('csi/view/(?P<id>\w+)/',
         'view_csi', name='view_csi'),
    path('csi/delete/(?P<id>\w+)/',
         'delete_csi', name='delete_csi'),
    # OVC Care - Form1A
    path('form1a/new/(?P<id>\d+)/',
         'form1a_events', name='form1a_events'),
    path('form1a/save/',
         'save_form1a', name='save_form1a'),
    path('form1a/edit/',
         'edit_form1a', name='edit_form1a'),
    path('form1a/view/',
         'view_form1a', name='view_form1a'),
    path('form1a/delete/',
         'delete_form1a', name='delete_form1a'),
    path('form1a/manage/',
         'manage_form1a_events', name='manage_form1a_events'),
    # OVC Care - Form1B
    path('form1b/new/(?P<id>\d+)/',
         'new_form1b', name='new_form1b'),
    # OVC Care - HHVA
    path('hhva/new/(?P<id>\d+)/',
         'new_hhva', name='new_hhva'),
    path('hhva/edit/(?P<id>\w+)/',
         'edit_hhva', name='edit_hhva'),
    path('hhva/view/(?P<id>\w+)/',
         'view_hhva', name='view_hhva'),
    path('hhva/delete/(?P<id>\w+)/',
         'delete_hhva', name='delete_hhva'),
    # Presidential Bursary
    path('bursary/new/(?P<id>\d+)/',
         'new_bursary', name='new_bursary'),
    path('case/(?P<case_id>[0-9A-Za-z_\-{32}\Z]+)/',
         'case_info', name='case_info'),

]
